### PR TITLE
WOOC-839 - update translations to add space

### PR DESCRIPTION
**Pull request by nunoteixeiranat**

### CODE REVIEW

**Review by GhDj — APPROVED** [review]

**Comment by PPmmesquita** [comment]
I have a question about this.
We're tricking the layout with a space on the texts, in my opinion what should have been done it's adding a `&nbsp` on the Atom or Molecule.

What you guys think?
@GhDj @nunoteixeiranat

**Comment by GhDj** [comment]
I would say to keep it as it is now, because if we apply a non-breaking-space on the vue side, prestashop  side may have a new space added.

**Comment by PPmmesquita** [comment]
We're adding a `space` on the beginning of a phrase... 
they for sure had the same problem we've!

**Comment by nunoteixeiranat** [comment]
Tecnically i'd go for the atom/molecule, but if there are concerns about
prestashop side or other then dont know

Em qua., 19 de abr. de 2023 às 09:16, Ghabri Djalel <
***@***.***> escreveu:

**Pull request merged**
